version: "2"

services:
    dfetch:
        build: dfetch
        environment:
            - DOCKER_URL=${DOCKER_URL}
        volumes: 
            - dfetch-data:/data 


    dmonweb:
        build: dmonweb
        depends_on:
            - dfetch
        volumes: 
            - dfetch-data:/data 
        ports:
            - 9090:5000

volumes:
    dfetch-data:
